name: CI/CD Pipeline - AWS ECR & ECS

on:
  push:
    branches:
      - feature/despliegue-ecs

jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Compilar y Subir Back-Despachos
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: microservice-despachos
          IMAGE_TAG: latest
        run: |
          cd back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          chmod +x mvnw
          ./mvnw clean package -DskipTests
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Compilar y Subir Back-Ventas
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: microservice-ventas
          IMAGE_TAG: latest
        run: |
          cd back-Ventas_SpringBoot/Springboot-API-REST
          chmod +x mvnw
          ./mvnw clean package -DskipTests
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Construir y Subir Frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: frontend
          IMAGE_TAG: latest
        run: |
          cd front_despacho
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-to-ecs:
    needs: build-and-push-ecr
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Descargar Task Definition de Despachos
        run: |
          aws ecs describe-task-definition --task-definition innovatech-backend-task --query taskDefinition > task-def-despachos.json

      - name: Reemplazar imagen por microservice-despachos
        id: render-despachos
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-def-despachos.json
          container-name: backend-container
          image: 429843885849.dkr.ecr.us-east-1.amazonaws.com/microservice-despachos:latest

      - name: Desplegar Despachos en ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-despachos.outputs.task-definition }}
          service: innovatech-service-back
          cluster: innovatech-cluster
          wait-for-service-stability: true

      - name: Descargar Task Definition de Ventas
        run: |
          aws ecs describe-task-definition --task-definition innovatech-ventas-task --query taskDefinition > task-def-ventas.json

      - name: Reemplazar imagen por microservice-ventas
        id: render-ventas
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-def-ventas.json
          container-name: ventas-container
          image: 429843885849.dkr.ecr.us-east-1.amazonaws.com/microservice-ventas:latest

      - name: Desplegar Ventas en ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-ventas.outputs.task-definition }}
          service: innovatech-service-ventas
          cluster: innovatech-cluster
          wait-for-service-stability: true

      - name: Descargar Task Definition de Frontend
        run: |
          aws ecs describe-task-definition --task-definition innovatech-frontend-task --query taskDefinition > task-def-front.json

      - name: Reemplazar imagen por Frontend en ECR
        id: render-front
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-def-front.json
          container-name: frontend-container
          image: 429843885849.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

      - name: Desplegar Frontend en ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-front.outputs.task-definition }}
          service: innovatech-service-front
          cluster: innovatech-cluster
          wait-for-service-stability: true
